version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html
    command: php artisan serve --host=0.0.0.0
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456

volumes:
  mysql_data:
    driver: local

networks:
  my-network:
    external: true
